version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    container_name: node18
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    tty: true
    command: yarn start
  django:
    build:
      context: "./backend/"
      dockerfile: "../docker/backend/Dockerfile"
    container_name: "django"
    working_dir: "/root/"
    tty: true
    volumes:
      - ./backend/app:/root/app
    ports:
      - "8000:8000"
